server:
  port: ${VALST_SERVER_PORT:8200}
  error:
    include-message: ${VALST_SERVER_ERROR_INCLUDE_MESSAGE:always}

spring:
  data:
    mongodb:
      uri: ${VALST_SPRING_DATA_MONGODB_URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
          jwk-set-uri:
        client-id:

auth:
  enabled: ${VALST_AUTH_ENABLED:true}
  project-authority-prefix: ${VALST_AUTH_PROJECT_AUTHORITY_PREFIX:PROJECT_}
  aac-claim: ${VALST_AUTH_AAC_VALIDATION_CLAIM:validation}
  aac-claim-projects: ${VALST_AUTH_AAC_VALIDATION_PROJECTS_LIST:projects}
  users: