server:
  port: ${SERVER_PORT:8200}
  error:
    include-message: ${ERROR_INCLUDE_MESSAGE:always}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  security:
    oauth2:
      client:
        registration:
          aac:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
        provider:
          aac:
            issuer-uri: ${ISSUER_URI}
            user-name-attribute: ${USER_NAME_ATTRIBUTE:preferred_username}
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
        client-id: ${CLIENT_ID}

auth:
  enabled: ${AUTH_ENABLED:true}
  project-authority-prefix: ${PROJECT_AUTHORITY_PREFIX:PROJECT_}
  aac-claim: ${AAC_CLAIM:validation}
  aac-claim-projects: ${AAC_CLAIM_PROJECTS:projects}
  users: