package it.smartcommunitylab.validationstorage.model;

import java.util.List;

import javax.persistence.Entity;
import javax.validation.Valid;

import org.springframework.data.annotation.Id;

@Valid
@Entity
public class Project {
    @Id
    @Autogenerated
    private String id;
    
    private String name;
    
    private String title;
    
    private List<DataPackage> dataPackages;
    
    private List<Store> stores;
    
    private List<Experiment> experiments;
    
    private String author;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public List<DataPackage> getDataPackages() {
        return dataPackages;
    }

    public void setDataPackages(List<DataPackage> dataPackages) {
        this.dataPackages = dataPackages;
    }

    public List<Store> getStores() {
        return stores;
    }

    public void setStores(List<Store> stores) {
        this.stores = stores;
    }

    public List<Experiment> getExperiments() {
        return experiments;
    }

    public void setExperiments(List<Experiment> experiments) {
        this.experiments = experiments;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }
    
}
